homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

login:
  path: /login
  defaults: { _controller: AppBundle:User:login }

logout:
  path: /logout

login_check:
  path: /login_check

allergen_add:
  path: /allergen/add
  defaults: { _controller: AppBundle:Allergen:add }

allergen_remove:
  path: /allergen/remove/{id}
  defaults: { _controller: AppBundle:Allergen:remove }
  requirements:
    id: '\d+'

allergen_index:
  path: /allergen/index
  defaults: { _controller: AppBundle:Allergen:index }

employee_add:
  path: /employee/{id}/add
  defaults: { _controller: AppBundle:Employee:add }
  requirements:
    id: '\d+'

employee_remove:
  path: /employee/{id}/remove/{employeeid}
  defaults: { _controller: AppBundle:Employee:remove }
  requirements:
    id: '\d+'
    employee: '\d+'

employee_index:
  path: /employee/{id}/index
  defaults: { _controller: AppBundle:Employee:index }
  requirements:
    id: '\d+'

employee_edit:
  path: /employee/{id}/edit/{employeeid}
  defaults: { _controller: AppBundle:Employee:edit }
  requirements:
    id: '\d+'
    employeeid: '\d+'

product_add:
  path: /product/{id}/add
  defaults: { _controller: AppBundle:Product:add }
  requirements:
    id: '\d+'

product_edit:
  path: /product/{id}/edit/{productid}
  defaults: { _controller: AppBundle:Product:edit }
  requirements:
    id: '\d+'
    productid: '\d+'

product_remove:
  path: /product/{id}/remove/{productid}
  defaults: { _controller: AppBundle:Product:remove }
  requirements:
    id: '\d+'
    productid: '\d+'

product_index:
  path: /product/{id}/index
  defaults: { _controller: AppBundle:Product:index }
  requirements:
    id: '\d+'

table_add:
  path: /table/{id}/add
  defaults: { _controller: AppBundle:Table:add }
  requirements:
    id: '\d+'

table_remove:
  path: /table/{id}/remove/{tableid}
  defaults: { _controller: AppBundle:Table:remove }
  requirements:
    id: '\d+'
    tableid: '\d+'

table_index:
  path: /table/{id}/index
  defaults: { _controller: AppBundle:Table:index }
  requirements:
    id: '\d+'

table_edit:
  path: /table/{id}/edit/{tableid}
  defaults: { _controller: AppBundle:Table:edit }
  requirements:
    id: '\d+'
    tableid: '\d+'

order_add:
  path: /order/{id}/add
  defaults: { _controller: AppBundle:Order:add }
  requirements:
    id: '\d+'

order_remove:
  path: /order/{id}/remove/{orderid}
  defaults: { _controller: AppBundle:Order:remove }
  requirements:
    id: '\d+'
    orderid: '\d+'

order_pay:
  path: /order/{id}/pay/{orderid}
  defaults: { _controller: AppBundle:Order:pay }
  requirements:
    id: '\d+'
    orderid: '\d+'

order_assign:
  path: /order/{id}/assign/{orderid}/{employeeid}
  defaults: { _controller: AppBundle:Order:assign }
  requirements:
    id: '\d+'
    orderid: '\d+'
    employeeid: '\d+'

order_index:
  path: /order/{id}/index
  defaults: { _controller: AppBundle:Order:index }
  requirements:
    id: '\d+'

order_get:
  path: /order/{orderid}/get
  defaults: { _controller: AppBundle:Order:order }
  requirements:
    orderid: '\d+'

restaurant_index:
  path: /restaurants/index
  defaults: { _controller: AppBundle:User:index }

restaurant_edit:
  path: /restaurant/{id}/edit
  defaults: { _controller: AppBundle:User:edit }
  requirements:
    id: '\d+'

clients_index:
  path: /clients/index
  defaults: { _controller: AppBundle:Admin:indexClients }

clients_edit:
  path: /client/{id}/edit
  defaults: { _controller: AppBundle:Admin:editClients }
  requirements:
    id: '\d+'