AppBundle\Entity\Order:
    type: entity
    table: Orders
    indexes:
        fk_employee_order_idx:
            columns:
                - employeeId
        fk_table_order_idx:
            columns:
                - tableId
        fk_restaurant_order_idx:
            columns:
                - restaurantId
    id:
        orderid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: orderId
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        paid:
            type: boolean
            nullable: false
            options:
                default: '0'
        served:
            type: boolean
            nullable: false
            options:
                default: '0'
        total:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
    manyToOne:
        employeeid:
            targetEntity: Employee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: orders
            joinColumns:
                employeeId:
                    referencedColumnName: employeeId
            orphanRemoval: false
        tableid:
            targetEntity: Table
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: orders
            joinColumns:
                tableId:
                    referencedColumnName: tableId
            orphanRemoval: true
        restaurantid:
            targetEntity: Restaurant
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: orders
            joinColumns:
                restaurantId:
                    referencedColumnName: restaurantId
            orphanRemoval: true
    oneToMany:
        orderlines:
            targetEntity: Orderline
            mappedBy: orderid
            cascade: { }
    lifecycleCallbacks: {  }
