AppBundle\Entity\Product:
    type: entity
    table: Products
    indexes:
        fk_restaurantId_product_idx:
            columns:
                - restaurantId
        fk_categoryId_product_idx:
            columns:
                - categoryId
    id:
        productid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: productId
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        name:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        published:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToOne:
        restaurantid:
            targetEntity: Restaurant
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: products
            ondelete: "CASCADE"
            joinColumns:
                restaurantId:
                    referencedColumnName: restaurantId
            orphanRemoval: true
        categoryid:
            targetEntity: Category
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: products
            ondelete: "CASCADE"
            joinColumns:
                categoryid:
                    referencedColumnName: categoryId
            orphanRemoval: true
    manyToMany:
        allergens:
            targetEntity: Allergen
            inversedBy: products
            joinTable:
                name: productcontains
                joinColumns:
                    productid:
                        referencedColumnName: productId
                inverseJoinColumns:
                    allergenid:
                        referencedColumnName: allergenId
    lifecycleCallbacks: {  }
