AppBundle\Entity\Productcontains:
    type: entity
    table: Productcontains
    indexes:
        fk_allergens_idx:
            columns:
                - allergenId
        fk_products_idx:
            columns:
                - productId
    id:
        productcontainsid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: productcontainsId
            generator:
                strategy: IDENTITY
    manyToOne:
        allergenid:
            targetEntity: Allergen
            cascade: [ "persist", "remove" ]
            fetch: LAZY
            mappedBy: null
            inversedBy: products
            joinColumns:
                allergenId:
                    referencedColumnName: allergenId
                    onDelete: CASCADE
            orphanRemoval: true
        productid:
            targetEntity: Product
            cascade: [ "persist", "remove" ]
            fetch: LAZY
            mappedBy: null
            inversedBy: allergens            
            joinColumns:
                productId:
                    referencedColumnName: productId
                    onDelete: CASCADE
            orphanRemoval: true
    lifecycleCallbacks: {  }
