AppBundle\Entity\Table:
    type: entity
    table: Tables
    indexes:
        fk_restaurant_table_idx:
            columns:
                - restaurantId
    id:
        tableid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: tableId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        restaurantid:
            targetEntity: Restaurant
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: tables
            joinColumns:
                restaurantId:
                    referencedColumnName: restaurantId
                    onDelete: CASCADE
            orphanRemoval: true
    oneToMany:
        orders:
            targetEntity: Order
            mappedBy: tableid
            cascade: { }
    lifecycleCallbacks: {  }
